_core:
  default_config_hash: cEG-oX5ZtnSn025nvTNB1G48_RXgC4C3geWA87PDafA
status: 2
pattern: '[node:field_profile_first_name] [node:field_profile_last_name]'
escape: false
preserve_titles: false
save: false
chunk: 50
dependencies:
  config:
    - node.type.osu_profile
new_content_behavior: 1
