_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 4b4e3289-1476-47f5-a800-cabc08bebae0
name: 'Gary R. Carlson, MD, College of Veterinary Medicine'
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
