_core:
  default_config_hash: CA_F3EeteXK_DAcgfUiaKvbmgr_KRgb45BPNvKSsZoo
langcode: en
domain: ''
roots: ''
shadowComponents: ''
ignore: '#toolbar-administration a,#block-madrone-sitebranding a,#madrone-primary-menu-container a,.block-superfish a,.block-menu a,.block-group-content-menu a'
hideIcon: ''
noRunIfPresent: ''
noRunIfAbsent: ''
themePreprocess: false
noAggregate: false
noIconOnImages: false
insertIconOutsideHiddenSpan: ''
purposeExternal: true
purposeExternalNoReferrer: false
purposeExternalNewWindow: false
purposeExternalSelector: ''
purposeExternalMessage: 'Link is external'
purposeExternalClass: ''
purposeExternalIconWrapperClass: ''
purposeExternalIconType: html
purposeExternalIconPosition: beforeend
purposeExternalIconClasses: ''
purposeDocument: true
purposeDocumentSelector: "[href^='/document/'], [href$='.pdf'], [href*='.pdf?'], [href$='.tex'], [href*='.tex?'], [href$='.doc'], [href$='.docx'], [href*='.doc?'], [href*='.docx?'], [href$='.ppt'], [href$='.pptx'], [href*='.ppt?'], [href*='.pptx?'], [href$='.odt'], [href*='.odt?'], [href$='.ods'], [href*='.ods?'], [href$='.odp'], [href*='.odp?'], [href^='https://docs.google']"
purposeDocumentMessage: 'Link downloads document'
purposeDocumentClass: ''
purposeDocumentIconWrapperClass: ''
purposeDocumentIconType: html
purposeDocumentIconPosition: beforeend
purposeDocumentIconClasses: ''
purposeDownload: true
purposeDownloadSelector: ''
purposeDownloadMessage: 'Link downloads file'
purposeDownloadClass: ''
purposeDownloadIconWrapperClass: ''
purposeDownloadIconType: html
purposeDownloadIconPosition: beforeend
purposeDownloadIconClasses: ''
purposeApp: true
purposeAppSelector: ''
purposeAppMessage: 'Link opens app'
purposeAppClass: ''
purposeAppIconWrapperClass: ''
purposeAppIconType: html
purposeAppIconPosition: beforeend
purposeAppIconClasses: ''
purposeMail: true
purposeMailSelector: null
purposeMailMessage: 'Link sends email'
purposeMailClass: ''
purposeMailIconWrapperClass: ''
purposeMailIconType: html
purposeMailIconPosition: beforeend
purposeMailIconClasses: ''
purposeTel: true
purposeTelSelector: null
purposeTelMessage: 'Link opens phone app'
purposeTelClass: ''
purposeTelIconWrapperClass: ''
purposeTelIconType: html
purposeTelIconPosition: beforeend
purposeTelIconClasses: ''
purposeNewWindow: true
purposeNewWindowSelector: null
purposeNewWindowMessage: 'Link opens in new window'
purposeNewWindowClass: ''
purposeNewWindowIconWrapperClass: ''
purposeNewWindowIconType: html
purposeNewWindowIconPosition: beforeend
purposeNewWindowIconClasses: ''
