shurly_base: 'https://beav.es'
shurly_redirect_page: ''
shurly_forbid_localhost: false
shurly_forbid_private_ips: false
shurly_forbid_unresolvable_hosts: false
shurly_forbid_ips: false
shurly_forbid_custom: false
shurly_custom_restriction: ''
shurly_gsb: 0
shurly_gsb_client: false
shurly_gsb_apikey: ''
shurly_length: 4
shurly_counter: 3249
shurly_index: kZ4oJ3Uwi5STqcpGNxfYgMQAdPWmsenh78XB26uLbEaRDzKrHVj9CyFtv
shurly_gsb_config_client: null
_core:
  default_config_hash: eFuGQ42Br5d2taQrwPXrtnMS0fRJ8qoOP5vpcSl2cGc
shurly_throttle:
  authenticated:
    rate: ''
    time: ''
    weight: '0'
  architect:
    rate: ''
    time: ''
    weight: '0'
  dx_administrator:
    rate: ''
    time: ''
    weight: '0'
  administrator:
    rate: ''
    time: ''
    weight: '0'
  earl:
    rate: ''
    time: ''
    weight: '0'
