_core:
  default_config_hash: 2FJpva5SHitDi7Wb1AHm8af_JZHM6yY6nuspPmnZgtc
back_to_top_prevent_on_mobile: true
back_to_top_prevent_in_admin: true
back_to_top_prevent_in_front: false
back_to_top_button_trigger: 1000.0
back_to_top_speed: 1200.0
back_to_top_button_place: 1
back_to_top_button_text: 'Back to top'
back_to_top_button_type: image
back_to_top_bg_color: '#d73f09'
back_to_top_border_color: '#d73f09'
back_to_top_hover_color: '#212529'
back_to_top_text_color: '#ffffff'
