_core:
  default_config_hash: AXUBMTvVtpcNp0jKjDaWjSHqMy6HjuUf7j4yVbXgazI
local_task_enabled_entity_types:
  - block_content
  - media
track_enabled_source_entity_types:
  - block_content
  - consumer
  - contact_message
  - content_moderation_state
  - crop
  - feeds_feed
  - feeds_subscription
  - group
  - group_config_wrapper
  - group_content
  - group_content_menu
  - media
  - menu_link_content
  - node
  - paragraph
  - path_alias
  - redirect
  - section_library_template
  - shortcut
  - sitewide_alert
  - taxonomy_term
  - vehicles
  - webform_submission
track_enabled_target_entity_types:
  - block_content
  - consumer
  - contact_message
  - content_moderation_state
  - crop
  - feeds_feed
  - feeds_subscription
  - group
  - group_config_wrapper
  - group_content
  - group_content_menu
  - media
  - menu_link_content
  - node
  - paragraph
  - path_alias
  - redirect
  - section_library_template
  - shortcut
  - sitewide_alert
  - taxonomy_term
  - vehicles
  - webform_submission
track_enabled_plugins:
  - block_field
  - ckeditor_image
  - dynamic_entity_reference
  - entity_embed
  - entity_reference
  - html_link
  - layout_builder
  - link
  - linkit
  - media_embed
track_enabled_base_fields: false
site_domains:
  - brabhamm.dev.oregonstate.edu
edit_warning_message_entity_types: {  }
delete_warning_message_entity_types: {  }
usage_controller_items_per_page: 25
