_core:
  default_config_hash: m7DQZLu4I7YywdeVXDa1jAbySy1oCRwxlWYHkfmr-ZA
translation_sync: true
search: false
type: remove
content_types:
  article: none
  page: user
  osu_profile: all
  osu_simple_tabs: all
  story: none
  test_all_the_things: none
  webform: none
  academic_calendar_item: none
  season_tickets: none
content_type_modes:
  article: {  }
  page:
    - full
  osu_profile:
    - full
  osu_simple_tabs:
    - full
    - simple_tab_content
    - test_simple_tab_view_mode
  story: {  }
  test_all_the_things: {  }
  webform: {  }
  academic_calendar_item: {  }
  season_tickets: {  }
