favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  use_default: true
madrone_companion_logo: osu
madrone_monsido_site_id: S-GELo0fuO5hXXDswnk4uw
madrone_use_default_404: 1
mardone_metatag_osu: 1
parent_site_name: ''
parent_site_url: ''
