_core:
  default_config_hash: XTMAktnp7qAlHn7vm0KwI1BffkPRlblfkxUFA51ScDM
langcode: en
search404_redirect_301: false
search404_do_custom_search: true
search404_custom_search_path: 'search/node?keys=@keys'
search404_jump: false
search404_skip_auto_search: false
search404_disable_error_message: true
search404_use_or: false
search404_use_customclue: ''
search404_use_search_engine: true
search404_ignore_extensions: 'htm html php'
search404_ignore_query: 'gif jpg jpeg bmp png'
search404_first: false
search404_first_on_paths: ''
search404_regex: ''
search404_page_text: ''
search404_do_google_cse: true
search404_do_search_by_page: false
search404_custom_error_message: ''
search404_page_redirect: ''
search404_page_title: 'Page not found'
search404_ignore: 'and or the'
search404_ignore_paths: ''
site_404: search404
search404_ignore_language: 0
