_core:
  default_config_hash: 1em5JafD7VbiJO44inPINOhOpDOLJPgSK5HSHEcA8_Y
translation_sync: true
search: true
type: hidden
content_types:
  page: user
  osu_profile: all
  academic_calendar: none
  academic_calendar_term: none
  announcement: none
  c_simple_tabs: all
  faq: none
  highlight: none
  program: none
  project: none
  story: none
  student_emails: none
  webform: none
content_type_modes:
  page:
    - full
  osu_profile:
    - full
  academic_calendar: {  }
  academic_calendar_term: {  }
  announcement: {  }
  c_simple_tabs:
    - c_simple_tabs_view_mode
  faq: {  }
  highlight: {  }
  program: {  }
  project: {  }
  story: {  }
  student_emails: {  }
  webform: {  }
