_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 9b10d0bf-1607-41e4-a8ee-ccdd0cb54203
name: 'Office of the Registrar'
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/2721
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
